apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-bus

namePrefix: prod-

commonLabels:
  environment: production

bases:
  - ../../base

patches:
  - path: patches.yaml

images:
  - name: agent_bus
    newName: agent_bus
    newTag: latest
