apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-bus

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis-deployment.yaml
  - postgres-deployment.yaml
  - api-deployment.yaml
  - cpu-worker-deployment.yaml
  - gpu-worker-job.yaml

commonLabels:
  app: agent-bus

images:
  - name: agent_bus
    newName: agent_bus
    newTag: latest
